### ISSUE TITLE
NATS configuration changes

### ISSUE THREAD

**Issue by jadamcrain** [openenergysolutions/openfmb.adapters#34]
1) Don't require all the profile names to be present - This invalidates old configurations whenever a profile is added

2) Make it possible to specify the mRID of the subject or use the "*" wildcard. The "<" wildcard isn't needed at this time.

Proposed format:

```
subscribe:
    - profile: <valid profile name>
      subject: { mRID | "*" }  # this forms the actual NATs subject name for the subscription
publish:
   - profile: <valid profile name>
     subject: { mRID | "*" }   # this is merely used as a filter internally to decide what should be published
```
